ARG     OS

FROM    ghcr.io/960018/php-fpm:$OS as builder

ARG     OS

USER    root

ENV     PHP_INI_DIR /usr/local/etc/php
ENV     PHP_CFLAGS "-fstack-protector-strong -fpic -fpie -O2 -ftree-vectorize -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -march=native"
ENV     PHP_CPPFLAGS "$PHP_CFLAGS"
ENV     PHP_LDFLAGS "-Wl,-O2 -pie"

COPY    php/docker-php-ext-enable /usr/local/bin/docker-php-ext-enable

COPY    php/clone/xdebugsrc/   /home/vairogs/extensions/xdebug/
#COPY    php/clone/runkit7src/ /home/vairogs/extensions/runkit7/

RUN     \
        set -eux \
&&      chmod -R 777 /usr/local/bin \
&&      mkdir --parents /home/vairogs/extensions

WORKDIR /home/vairogs/extensions

RUN     \
        set -eux \
&&      apt-get update \
&&      apt-get upgrade -y \
&&      apt-get install -y --no-install-recommends autoconf dpkg-dev dpkg file g++ gcc libc-dev make pkgconf re2c bison \
&&      ( \
            cd xdebug \
            &&  phpize \
            &&  autoupdate \
            &&  ./configure --enable-xdebug \
            &&  make -j "$(expr $(nproc) / 3)" \
            &&  make install \
            &&  cd .. || exit \
        ) \
&&      docker-php-ext-enable xdebug \
# &&      ( \
#             cd  runkit7 \
#             &&  phpize \
#             &&  ./configure \
#             &&  make -j "$(expr $(nproc) / 3)" \
#             &&  make install \
#             &&  cd .. || exit \
#         ) \
# &&      docker-php-ext-enable runkit7 \
&&      echo xdebug.mode=debug,coverage >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
&&      echo xdebug.discover_client_host=0 >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
&&      echo xdebug.client_host=host.docker.internal >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
&&      echo xdebug.log=/tmp/xdebug.log >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
# &&      echo runkit.internal_override=1 >> /usr/local/etc/php/conf.d/docker-php-ext-runkit7.ini \
&&      echo 'alias upd="composer update -nW --ignore-platform-reqs"' >> /home/vairogs/.bashrc \
&&      echo 'alias ins="composer install -n --ignore-platform-reqs"' >> /home/vairogs/.bashrc \
&&      echo 'alias req="composer require -nW --ignore-platform-reqs"' >> /home/vairogs/.bashrc \
&&      echo 'alias rem="composer remove -nW --ignore-platform-reqs"' >> /home/vairogs/.bashrc \
&&      apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false autoconf dpkg-dev g++ gcc file libc-dev make pkgconf re2c bison \
&&      apt-get autoremove -y --purge \
&&      rm -rf \
            /*.deb \
            /home/vairogs/*.deb \
            /home/vairogs/*.gz \
            /home/vairogs/extensions \
            /home/vairogs/installer \
            /tmp/* \
            /usr/local/bin/docker-php-ext-enable \
            /usr/local/bin/phpdbg \
            /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini \
            /usr/local/etc/php/php.ini-development \
            /usr/local/etc/php/php.ini-production \
            /usr/local/php/man/* \
            /usr/src/php \
            /var/cache/* \
            ~/.pearrc \
            /tmp/* \
            /usr/share/vim/vim90/doc \
            /usr/share/man/* \
&&      chown -R vairogs:vairogs /home/vairogs

COPY    php/exts/opcache.jit.ini /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini

WORKDIR /var/www/html

USER    vairogs

CMD     ["sh", "-c", "php-fpm && /bin/bash"]

FROM    scratch

COPY    --from=builder / / 

SHELL   ["/bin/bash", "-o", "pipefail", "-c"]

LABEL   maintainer="support+docker@vairogs.com"
LABEL   org.opencontainers.image.source https://github.com/960018/docker

ENV     PHP_VERSION 8.3.0-dev
ENV     PHP_INI_DIR /usr/local/etc/php
ENV     PHP_CFLAGS "-fstack-protector-strong -fpic -fpie -O2 -ftree-vectorize -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -march=native"
ENV     PHP_CPPFLAGS "$PHP_CFLAGS"
ENV     PHP_LDFLAGS "-Wl,-O2 -pie"
ENV     container=docker
ENV     DEBIAN_FRONTEND=noninteractive
ENV     PHP_CS_FIXER_IGNORE_ENV 1

STOPSIGNAL SIGQUIT

WORKDIR /var/www/html

USER    vairogs

EXPOSE  9000

CMD     ["sh", "-c", "php-fpm && /bin/bash"]
