networks:

    frontend:
        name: frontend

    backend:
        name: backend

volumes:

    esdata:

services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
        container_name: elasticsearch
        networks:
            - backend
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
            - "ES_HEAP_SIZE=64m"
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - 127.0.0.1:9200:9200
            - 127.0.0.1:9300:9300
